-- AppKorea / HanQuoc Classroom - FULL vocabulary hotfix for Sơ cấp 1 (Bài 1-15)
-- Generated from the user-provided textbook. Non-destructive: UPSERT only; no DELETE.
-- Existing class_vocabulary references and prior IDs are preserved.
SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (1, '소개', 'Giới thiệu', '["N이에요/예요","N은/는"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (2, '학교', 'Trường học', '["이/그/저","N이/가 있어요/없어요"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (3, '일상생활', 'Sinh hoạt hàng ngày', '["N을/를","N에서"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (4, '날짜와 요일', 'Ngày và thứ', '["N에","부터/까지"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (5, '하루 일과', 'Công việc trong ngày', '["A/V-고","몇 시에"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (6, '주말', 'Cuối tuần', '["V-고 싶어요","V-(으)ㄹ 거예요"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (7, '물건 사기 (1)', 'Mua sắm (1)', '["N 주세요","얼마예요?"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (8, '음식', 'Thức ăn', '["N하고/N과/와","V-(으)세요"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (9, '집', 'Nhà cửa', '["N 앞/뒤/옆에","A/V-아서/어서"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (10, '가족', 'Gia đình', '["N의","V-(으)세요 (kính ngữ)"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (11, '날씨', 'Thời tiết', '["A/V-지만","A/V-네요"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (12, '전화 (1)', 'Điện thoại (1)', '["V-아/어 주세요","N한테/에게"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (13, '생일', 'Sinh nhật', '["V-(으)ㄹ까요?","A/V-아서/어서"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (14, '취미', 'Sở thích', '["V-(으)ㄹ 수 있어요","N을/를 좋아해요"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);
INSERT INTO textbook_lessons (id, title, topic, grammar, source_name) VALUES (15, '교통 (1)', 'Giao thông (1)', '["N(으)로","N에서 N까지"]', 'Tiếng Hàn Tổng Hợp Dành Cho Người Việt Nam – Sơ cấp 1') ON DUPLICATE KEY UPDATE title=VALUES(title), topic=VALUES(topic), grammar=VALUES(grammar), source_name=VALUES(source_name);

INSERT INTO vocabulary (lesson_id, korean, romanization, meaning_vi, example_kr, example_vi) VALUES
(1, '한국', NULL, 'Hàn Quốc', NULL, NULL),
(1, '베트남', NULL, 'Việt Nam', NULL, NULL),
(1, '말레이시아', NULL, 'Malaysia', NULL, NULL),
(1, '일본', NULL, 'Nhật', NULL, NULL),
(1, '미국', NULL, 'Mỹ', NULL, NULL),
(1, '중국', NULL, 'Trung Quốc', NULL, NULL),
(1, '태국', NULL, 'Thái Lan', NULL, NULL),
(1, '호주', NULL, 'Úc', NULL, NULL),
(1, '몽골', NULL, 'Mông Cổ', NULL, NULL),
(1, '인도네시아', NULL, 'Indonesia', NULL, NULL),
(1, '필리핀', NULL, 'Philippin', NULL, NULL),
(1, '인도', NULL, 'Ấn Độ', NULL, NULL),
(1, '영국', NULL, 'Anh', NULL, NULL),
(1, '독일', NULL, 'Đức', NULL, NULL),
(1, '프랑스', NULL, 'Pháp', NULL, NULL),
(1, '러시아', NULL, 'Nga', NULL, NULL),
(1, '학생', NULL, 'học sinh', NULL, NULL),
(1, '회사원', NULL, 'nhân viên công ty', NULL, NULL),
(1, '은행원', NULL, 'nhân viên ngân hàng', NULL, NULL),
(1, '선생님', NULL, 'giáo viên', NULL, NULL),
(1, '의사', NULL, 'bác sĩ', NULL, NULL),
(1, '공무원', NULL, 'công chức', NULL, NULL),
(1, '관광 가이드', NULL, 'hướng dẫn viên du lịch', NULL, NULL),
(1, '주부', NULL, 'nội trợ', NULL, NULL),
(1, '약사', NULL, 'dược sĩ', NULL, NULL),
(1, '운전기사', NULL, 'lái xe', NULL, NULL),
(1, '안녕하세요?', NULL, 'Xin chào?', NULL, NULL),
(1, '안녕하십니까?', NULL, 'Xin chào?', NULL, NULL),
(1, '안녕히 가세요.', NULL, 'Xin tạm biệt. (Đi về bình an)', NULL, NULL),
(1, '안녕히 계세요.', NULL, 'Xin tạm biệt. (Ở lại bình an)', NULL, NULL),
(1, '처음 뵙겠습니다.', NULL, 'Rất hân hạnh.', NULL, NULL),
(1, '반갑습니다.', NULL, 'Rất vui được gặp.', NULL, NULL),
(1, '국어국문학과', NULL, 'khoa ngữ văn', NULL, NULL),
(1, '국적', NULL, 'quốc tịch', NULL, NULL),
(1, '네', NULL, 'vâng', NULL, NULL),
(1, '대학교', NULL, 'trường đại học', NULL, NULL),
(1, '대학생', NULL, 'sinh viên', NULL, NULL),
(1, '보기', NULL, 'mẫu, ví dụ', NULL, NULL),
(1, '씨', NULL, 'bạn--', NULL, NULL),
(1, '아니요', NULL, 'không', NULL, NULL),
(1, '이', NULL, 'này', NULL, NULL),
(1, '이름', NULL, 'tên', NULL, NULL),
(1, '이메일', NULL, 'email, thư điện tử', NULL, NULL),
(1, '저', NULL, 'tôi', NULL, NULL),
(1, '전화', NULL, 'điện thoại', NULL, NULL),
(1, '제', NULL, 'của tôi', NULL, NULL),
(1, '주소', NULL, 'địa chỉ', NULL, NULL),
(1, '직업', NULL, 'nghề nghiệp', NULL, NULL),
(1, '학과', NULL, 'bộ môn', NULL, NULL),
(1, '학번', NULL, 'mã số sinh viên', NULL, NULL),
(1, '학생증', NULL, 'thẻ sinh viên', NULL, NULL),
(1, '한국어', NULL, 'tiếng Hàn', NULL, NULL),
(1, '한국어과', NULL, 'khoa Hàn ngữ', NULL, NULL),
(2, '학교', NULL, 'trường học', NULL, NULL),
(2, '도서관', NULL, 'thư viện', NULL, NULL),
(2, '식당', NULL, 'nhà ăn, nhà hàng', NULL, NULL),
(2, '호텔', NULL, 'khách sạn', NULL, NULL),
(2, '극장', NULL, 'nhà hát', NULL, NULL),
(2, '우체국', NULL, 'bưu điện', NULL, NULL),
(2, '병원', NULL, 'bệnh viện', NULL, NULL),
(2, '은행', NULL, 'ngân hàng', NULL, NULL),
(2, '백화점', NULL, 'cửa hàng bách hóa', NULL, NULL),
(2, '약국', NULL, 'hiệu thuốc', NULL, NULL),
(2, '가게', NULL, 'cửa tiệm, cửa hàng', NULL, NULL),
(2, '사무실', NULL, 'văn phòng', NULL, NULL),
(2, '강의실', NULL, 'giảng đường, phòng học', NULL, NULL),
(2, '교실', NULL, 'phòng học', NULL, NULL),
(2, '화장실', NULL, 'phòng vệ sinh', NULL, NULL),
(2, '휴게실', NULL, 'phòng nghỉ', NULL, NULL),
(2, '랩실(어학실)', NULL, 'phòng lab', NULL, NULL),
(2, '동아리방', NULL, 'phòng sinh hoạt câu lạc bộ', NULL, NULL),
(2, '체육관', NULL, 'nhà thi đấu thể thao', NULL, NULL),
(2, '운동장', NULL, 'sân vận động', NULL, NULL),
(2, '강당', NULL, 'giảng đường lớn, hội trường', NULL, NULL),
(2, '학생 식당', NULL, 'nhà ăn học sinh', NULL, NULL),
(2, '세미나실', NULL, 'phòng hội thảo', NULL, NULL),
(2, '서점', NULL, 'hiệu sách', NULL, NULL),
(2, '책상', NULL, 'cái bàn', NULL, NULL),
(2, '의자', NULL, 'cái ghế', NULL, NULL),
(2, '칠판', NULL, 'bảng', NULL, NULL),
(2, '문', NULL, 'cửa', NULL, NULL),
(2, '창문', NULL, 'cửa sổ', NULL, NULL),
(2, '시계', NULL, 'đồng hồ', NULL, NULL),
(2, '가방', NULL, 'cặp sách', NULL, NULL),
(2, '컴퓨터', NULL, 'máy vi tính', NULL, NULL),
(2, '책', NULL, 'sách', NULL, NULL),
(2, '공책', NULL, 'vở', NULL, NULL),
(2, '사전', NULL, 'từ điển', NULL, NULL),
(2, '지우개', NULL, 'hòn tẩy, cục tẩy', NULL, NULL),
(2, '지도', NULL, 'bản đồ', NULL, NULL),
(2, '펜', NULL, 'bút, viết', NULL, NULL),
(2, '필통', NULL, 'hộp bút', NULL, NULL),
(2, '거기', NULL, 'ở đó', NULL, NULL),
(2, '그것', NULL, 'cái đó', NULL, NULL),
(2, '라디오', NULL, 'đài, radio', NULL, NULL),
(2, '많이', NULL, 'nhiều', NULL, NULL),
(2, '명동', NULL, 'khu Myeongdong', NULL, NULL),
(2, '없다', NULL, 'không có', NULL, NULL),
(2, '여기', NULL, 'ở đây', NULL, NULL),
(2, '이것', NULL, 'cái này', NULL, NULL)
ON DUPLICATE KEY UPDATE romanization=VALUES(romanization), meaning_vi=VALUES(meaning_vi);

INSERT INTO vocabulary (lesson_id, korean, romanization, meaning_vi, example_kr, example_vi) VALUES
(2, '있다', NULL, 'có', NULL, NULL),
(2, '저것', NULL, 'cái kia', NULL, NULL),
(2, '저기', NULL, 'ở kia', NULL, NULL),
(2, '텔레비전', NULL, 'ti vi', NULL, NULL),
(3, '가다', NULL, 'đi', NULL, NULL),
(3, '오다', NULL, 'đến', NULL, NULL),
(3, '자다', NULL, 'ngủ', NULL, NULL),
(3, '먹다', NULL, 'ăn', NULL, NULL),
(3, '마시다', NULL, 'uống', NULL, NULL),
(3, '이야기하다', NULL, 'nói chuyện', NULL, NULL),
(3, '읽다', NULL, 'đọc', NULL, NULL),
(3, '듣다', NULL, 'nghe', NULL, NULL),
(3, '보다', NULL, 'nhìn, xem', NULL, NULL),
(3, '일하다', NULL, 'làm việc', NULL, NULL),
(3, '공부하다', NULL, 'học', NULL, NULL),
(3, '운동하다', NULL, 'luyện tập thể thao', NULL, NULL),
(3, '쉬다', NULL, 'nghỉ, nghỉ ngơi', NULL, NULL),
(3, '만나다', NULL, 'gặp gỡ', NULL, NULL),
(3, '사다', NULL, 'mua', NULL, NULL),
(3, '좋아하다', NULL, 'thích', NULL, NULL),
(3, '크다', NULL, 'to, lớn', NULL, NULL),
(3, '작다', NULL, 'nhỏ', NULL, NULL),
(3, '많다', NULL, 'nhiều', NULL, NULL),
(3, '적다', NULL, 'ít', NULL, NULL),
(3, '좋다', NULL, 'tốt', NULL, NULL),
(3, '나쁘다', NULL, 'xấu, tồi', NULL, NULL),
(3, '재미있다', NULL, 'hay, thú vị', NULL, NULL),
(3, '재미없다', NULL, 'không hay', NULL, NULL),
(3, '차', NULL, 'trà', NULL, NULL),
(3, '커피', NULL, 'cà phê', NULL, NULL),
(3, '빵', NULL, 'bánh mì', NULL, NULL),
(3, '우유', NULL, 'sữa', NULL, NULL),
(3, '영화', NULL, 'phim', NULL, NULL),
(3, '음악', NULL, 'âm nhạc', NULL, NULL),
(3, '신문', NULL, 'báo', NULL, NULL),
(3, '친구', NULL, 'bạn, bạn bè', NULL, NULL),
(3, '무엇', NULL, 'cái gì', NULL, NULL),
(3, '어디', NULL, 'đâu', NULL, NULL),
(3, '누구', NULL, 'ai', NULL, NULL),
(3, '언제', NULL, 'khi nào, bao giờ', NULL, NULL),
(3, '공원', NULL, 'công viên', NULL, NULL),
(3, '노래', NULL, 'bài hát', NULL, NULL),
(3, '대한빌딩', NULL, 'tòa nhà Dae Han', NULL, NULL),
(3, '방', NULL, 'phòng', NULL, NULL),
(3, '사과', NULL, 'táo', NULL, NULL),
(3, '시내', NULL, 'trung tâm thành phố', NULL, NULL),
(3, '시장', NULL, 'chợ', NULL, NULL),
(3, '식사하다', NULL, 'dùng bữa', NULL, NULL),
(3, '아이스크림', NULL, 'kem', NULL, NULL),
(3, '아주', NULL, 'rất', NULL, NULL),
(3, '여행', NULL, 'du lịch', NULL, NULL),
(3, '전화하다', NULL, 'gọi điện thoại', NULL, NULL),
(3, '지금', NULL, 'bây giờ', NULL, NULL),
(3, '축구를 하다', NULL, 'đá bóng', NULL, NULL),
(3, '카페', NULL, 'quán cà phê', NULL, NULL),
(3, '헬스클럽', NULL, 'câu lạc bộ thể dục thể thao', NULL, NULL),
(4, '월요일', NULL, 'thứ hai', NULL, NULL),
(4, '화요일', NULL, 'thứ ba', NULL, NULL),
(4, '수요일', NULL, 'thứ tư', NULL, NULL),
(4, '목요일', NULL, 'thứ năm', NULL, NULL),
(4, '금요일', NULL, 'thứ sáu', NULL, NULL),
(4, '토요일', NULL, 'thứ bảy', NULL, NULL),
(4, '일요일', NULL, 'chủ nhật', NULL, NULL),
(4, '년', NULL, 'năm', NULL, NULL),
(4, '월', NULL, 'tháng', NULL, NULL),
(4, '일', NULL, 'ngày', NULL, NULL),
(4, '시', NULL, 'giờ', NULL, NULL),
(4, '일월', NULL, 'tháng giêng (một)', NULL, NULL),
(4, '이월', NULL, 'tháng hai', NULL, NULL),
(4, '삼월', NULL, 'tháng ba', NULL, NULL),
(4, '사월', NULL, 'tháng tư', NULL, NULL),
(4, '오월', NULL, 'tháng năm', NULL, NULL),
(4, '유월', NULL, 'tháng sáu', NULL, NULL),
(4, '칠월', NULL, 'tháng bảy', NULL, NULL),
(4, '팔월', NULL, 'tháng tám', NULL, NULL),
(4, '구월', NULL, 'tháng chín', NULL, NULL),
(4, '시월', NULL, 'tháng mười', NULL, NULL),
(4, '십일월', NULL, 'tháng mười một', NULL, NULL),
(4, '십이월', NULL, 'tháng mười hai', NULL, NULL),
(4, '그저께', NULL, 'hôm kia', NULL, NULL),
(4, '어제', NULL, 'hôm qua', NULL, NULL),
(4, '오늘', NULL, 'hôm nay', NULL, NULL),
(4, '내일', NULL, 'ngày mai', NULL, NULL),
(4, '모레', NULL, 'ngày kia', NULL, NULL),
(4, '지난해(작년)', NULL, 'năm trước, năm ngoái', NULL, NULL),
(4, '올해(금년)', NULL, 'năm nay', NULL, NULL),
(4, '다음 해(내년)', NULL, 'năm sau', NULL, NULL),
(4, '지난달', NULL, 'tháng trước', NULL, NULL),
(4, '이번 달', NULL, 'tháng này', NULL, NULL),
(4, '다음 달', NULL, 'tháng sau', NULL, NULL),
(4, '지난주', NULL, 'tuần trước', NULL, NULL),
(4, '이번 주', NULL, 'tuần này', NULL, NULL),
(4, '다음 주', NULL, 'tuần sau', NULL, NULL),
(4, '평일(주중)', NULL, 'ngày thường (trong tuần)', NULL, NULL),
(4, '주말', NULL, 'cuối tuần', NULL, NULL),
(4, '강사', NULL, 'giảng viên', NULL, NULL),
(4, '계획표', NULL, 'bảng kế hoạch', NULL, NULL),
(4, '구경하다', NULL, 'ngắm, xem', NULL, NULL),
(4, '그리고', NULL, 'và', NULL, NULL),
(4, '등산', NULL, 'việc leo núi', NULL, NULL)
ON DUPLICATE KEY UPDATE romanization=VALUES(romanization), meaning_vi=VALUES(meaning_vi);

INSERT INTO vocabulary (lesson_id, korean, romanization, meaning_vi, example_kr, example_vi) VALUES
(4, '명절', NULL, 'ngày lễ', NULL, NULL),
(4, '방학', NULL, 'kỳ nghỉ (của học sinh)', NULL, NULL),
(4, '산', NULL, 'núi', NULL, NULL),
(4, '생일 파티', NULL, 'tiệc sinh nhật', NULL, NULL),
(4, '설날', NULL, 'ngày Tết', NULL, NULL),
(4, '숙제', NULL, 'bài tập', NULL, NULL),
(4, '시험', NULL, 'kỳ thi, kỳ kiểm tra', NULL, NULL),
(4, '아르바이트', NULL, 'sự làm thêm', NULL, NULL),
(4, '아름답다', NULL, 'đẹp', NULL, NULL),
(4, '안내', NULL, 'sự hướng dẫn', NULL, NULL),
(4, '졸업하다', NULL, 'tốt nghiệp', NULL, NULL),
(4, '층', NULL, 'tầng', NULL, NULL),
(4, '커피숍', NULL, 'quán cà phê', NULL, NULL),
(4, '크리스마스', NULL, 'Giáng sinh', NULL, NULL),
(4, '파티를 하다', NULL, 'tổ chức tiệc', NULL, NULL),
(4, '한글날', NULL, 'ngày kỷ niệm chữ Hangeul', NULL, NULL),
(4, '호', NULL, 'số (phòng)', NULL, NULL),
(4, '회의하다', NULL, 'họp, hội nghị', NULL, NULL),
(4, '휴가', NULL, 'kỳ nghỉ', NULL, NULL),
(5, '오전', NULL, 'buổi sáng', NULL, NULL),
(5, '오후', NULL, 'buổi chiều', NULL, NULL),
(5, '낮', NULL, 'ban ngày', NULL, NULL),
(5, '밤', NULL, 'ban đêm', NULL, NULL),
(5, '아침', NULL, 'sáng', NULL, NULL),
(5, '점심', NULL, 'trưa', NULL, NULL),
(5, '저녁', NULL, 'tối', NULL, NULL),
(5, '새벽', NULL, 'sáng sớm', NULL, NULL),
(5, '분', NULL, 'phút', NULL, NULL),
(5, '초', NULL, 'giây', NULL, NULL),
(5, '일어나다', NULL, 'thức dậy', NULL, NULL),
(5, '이를 닦다', NULL, 'đánh răng', NULL, NULL),
(5, '세수하다', NULL, 'rửa mặt', NULL, NULL),
(5, '다니다', NULL, 'đi lại (có tính thường xuyên)', NULL, NULL),
(5, '배우다', NULL, 'học', NULL, NULL),
(5, '숙제하다', NULL, 'làm bài tập', NULL, NULL),
(5, '청소하다', NULL, 'dọn vệ sinh', NULL, NULL),
(5, '목욕하다', NULL, 'tắm', NULL, NULL),
(5, '출근하다', NULL, 'đi làm', NULL, NULL),
(5, '퇴근하다', NULL, 'tan tầm', NULL, NULL),
(5, '시작하다', NULL, 'bắt đầu', NULL, NULL),
(5, '끝나다', NULL, 'xong, kết thúc', NULL, NULL),
(5, '고향', NULL, 'quê hương', NULL, NULL),
(5, '날', NULL, 'ngày', NULL, NULL),
(5, '남자', NULL, 'nam giới', NULL, NULL),
(5, '노래방', NULL, 'quán karaoke', NULL, NULL),
(5, '받다', NULL, 'nhận', NULL, NULL),
(5, '부모님', NULL, 'bố mẹ', NULL, NULL),
(5, '수업', NULL, 'giờ học, buổi học', NULL, NULL),
(5, '시험을 보다', NULL, 'thi', NULL, NULL),
(5, '여자', NULL, 'phụ nữ', NULL, NULL),
(5, '영문과', NULL, 'khoa Ngữ văn Anh', NULL, NULL),
(5, '영어', NULL, 'tiếng Anh', NULL, NULL),
(5, '운전하다', NULL, 'lái xe', NULL, NULL),
(5, '인터넷', NULL, 'internet', NULL, NULL),
(5, '일기', NULL, 'nhật kí', NULL, NULL),
(5, '집', NULL, 'nhà', NULL, NULL),
(5, '출근', NULL, 'đi làm', NULL, NULL),
(5, '출발하다', NULL, 'xuất phát', NULL, NULL),
(5, '후', NULL, 'sau, sau khi', NULL, NULL),
(5, '회사', NULL, 'công ty', NULL, NULL),
(5, '회의', NULL, 'họp, hội thảo', NULL, NULL),
(5, 'PC방', NULL, 'dịch vụ vi tính, quán internet', NULL, NULL),
(6, '무슨', NULL, 'gì', NULL, NULL),
(6, '어떤', NULL, '(thế) nào', NULL, NULL),
(6, '어느', NULL, 'nào', NULL, NULL),
(6, '등산하다', NULL, 'leo núi', NULL, NULL),
(6, '영화를 보다', NULL, 'xem phim', NULL, NULL),
(6, '여행하다', NULL, 'du lịch', NULL, NULL),
(6, '쇼핑하다', NULL, 'mua sắm', NULL, NULL),
(6, '수영하다', NULL, 'bơi', NULL, NULL),
(6, '외식하다', NULL, 'ăn ngoài', NULL, NULL),
(6, '친구를 만나다', NULL, 'gặp bạn', NULL, NULL),
(6, '산책하다', NULL, 'đi dạo bộ', NULL, NULL),
(6, '소풍가다', NULL, 'đi dã ngoại', NULL, NULL),
(6, '책을 읽다', NULL, 'đọc sách', NULL, NULL),
(6, '가수', NULL, 'ca sĩ', NULL, NULL),
(6, '개', NULL, 'con chó', NULL, NULL),
(6, '고양이', NULL, 'con mèo', NULL, NULL),
(6, '공포 영화', NULL, 'phim kinh dị', NULL, NULL),
(6, '김밥', NULL, 'món Kimbap (cơm cuốn lá kim)', NULL, NULL),
(6, '나무', NULL, 'cây', NULL, NULL),
(6, '낚시', NULL, 'câu cá', NULL, NULL),
(6, '동물', NULL, 'động vật', NULL, NULL),
(6, '드라마', NULL, 'phim truyền hình', NULL, NULL),
(6, '딸기', NULL, 'quả dâu', NULL, NULL),
(6, '바다', NULL, 'biển', NULL, NULL),
(6, '배', NULL, 'quả lê', NULL, NULL),
(6, '보내다', NULL, 'trải qua', NULL, NULL),
(6, '빨래하다', NULL, 'giặt đồ', NULL, NULL),
(6, '새', NULL, 'chim', NULL, NULL),
(6, '선물', NULL, 'quà tặng', NULL, NULL),
(6, '싫어하다', NULL, 'ghét', NULL, NULL),
(6, '액션 영화', NULL, 'phim hành động', NULL, NULL),
(6, '요리하다', NULL, 'nấu ăn', NULL, NULL),
(6, '일찍', NULL, 'sớm', NULL, NULL),
(6, '춤을 추다', NULL, 'nhảy múa', NULL, NULL),
(6, '치다', NULL, 'đánh, chơi (cầu)', NULL, NULL),
(6, '포도', NULL, 'quả nho', NULL, NULL),
(6, '피곤하다', NULL, 'mệt nhọc', NULL, NULL),
(7, '개', NULL, 'cái', NULL, NULL)
ON DUPLICATE KEY UPDATE romanization=VALUES(romanization), meaning_vi=VALUES(meaning_vi);

INSERT INTO vocabulary (lesson_id, korean, romanization, meaning_vi, example_kr, example_vi) VALUES
(7, '명', NULL, 'người', NULL, NULL),
(7, '사람', NULL, 'người', NULL, NULL),
(7, '마리', NULL, 'con', NULL, NULL),
(7, '잔', NULL, 'chén, cốc, ly', NULL, NULL),
(7, '대', NULL, 'chiếc', NULL, NULL),
(7, '병', NULL, 'bình, chai', NULL, NULL),
(7, '켤레', NULL, 'đôi', NULL, NULL),
(7, '권', NULL, 'quyển', NULL, NULL),
(7, '장', NULL, 'trang', NULL, NULL),
(7, '하나', NULL, 'một', NULL, NULL),
(7, '둘', NULL, 'hai', NULL, NULL),
(7, '셋', NULL, 'ba', NULL, NULL),
(7, '넷', NULL, 'bốn', NULL, NULL),
(7, '다섯', NULL, 'năm', NULL, NULL),
(7, '스물', NULL, 'hai mươi', NULL, NULL),
(7, '스물하나', NULL, 'hai mươi mốt', NULL, NULL),
(7, '여러', NULL, 'nhiều', NULL, NULL),
(7, '과일', NULL, 'hoa quả', NULL, NULL),
(7, '채소', NULL, 'rau', NULL, NULL),
(7, '음료수', NULL, 'thức uống', NULL, NULL),
(7, '옷', NULL, 'quần áo', NULL, NULL),
(7, '바지', NULL, 'quần', NULL, NULL),
(7, '치마', NULL, 'váy', NULL, NULL),
(7, '구두', NULL, 'giày', NULL, NULL),
(7, '모자', NULL, 'mũ', NULL, NULL),
(7, '과자', NULL, 'bánh, kẹo', NULL, NULL),
(7, '귤', NULL, 'quả quýt', NULL, NULL),
(7, '디자인', NULL, 'thiết kế', NULL, NULL),
(7, '마트', NULL, 'siêu thị nhỏ', NULL, NULL),
(7, '망고', NULL, 'xoài', NULL, NULL),
(7, '문구점', NULL, 'cửa hàng văn phòng phẩm', NULL, NULL),
(7, '생선', NULL, 'cá', NULL, NULL),
(7, '세일', NULL, 'hạ giá', NULL, NULL),
(7, '소설책', NULL, 'sách tiểu thuyết', NULL, NULL),
(7, '수박', NULL, 'dưa hấu', NULL, NULL),
(7, '전자상가', NULL, 'khu bán hàng điện tử', NULL, NULL),
(7, '주스', NULL, 'nước hoa quả, sinh tố', NULL, NULL),
(7, '카메라', NULL, 'máy ảnh', NULL, NULL),
(7, '티셔츠', NULL, 'áo sơ mi', NULL, NULL),
(8, '밥', NULL, 'cơm', NULL, NULL),
(8, '국', NULL, 'canh', NULL, NULL),
(8, '김치', NULL, 'Kim chi', NULL, NULL),
(8, '불고기', NULL, 'món bulgogi', NULL, NULL),
(8, '된장찌개', NULL, 'canh Doen-jang, canh tương', NULL, NULL),
(8, '비빔밥', NULL, 'Bibimbap (món cơm trộn)', NULL, NULL),
(8, '냉면', NULL, 'naeng-myeon (món mì lạnh)', NULL, NULL),
(8, '떡', NULL, 'bánh tteok', NULL, NULL),
(8, '라면', NULL, 'mì gói', NULL, NULL),
(8, '삼겹살', NULL, 'món thịt ba chỉ nướng', NULL, NULL),
(8, '김치찌개', NULL, 'canh kim chi', NULL, NULL),
(8, '갈비탕', NULL, 'súp sườn bò', NULL, NULL),
(8, '삼계탕', NULL, 'gà tần sâm', NULL, NULL),
(8, '볶음밥', NULL, 'cơm chiên, cơm rang', NULL, NULL),
(8, '갈비', NULL, 'món sườn nướng', NULL, NULL),
(8, '국수', NULL, 'mì, bún', NULL, NULL),
(8, '맛있다', NULL, 'ngon', NULL, NULL),
(8, '맛없다', NULL, 'không ngon', NULL, NULL),
(8, '달다', NULL, 'ngọt', NULL, NULL),
(8, '쓰다', NULL, 'đắng', NULL, NULL),
(8, '짜다', NULL, 'mặn', NULL, NULL),
(8, '시다', NULL, 'chua', NULL, NULL),
(8, '맵다', NULL, 'cay', NULL, NULL),
(8, '싱겁다', NULL, 'nhạt', NULL, NULL),
(8, '숟가락', NULL, 'thìa, muỗng', NULL, NULL),
(8, '젓가락', NULL, 'đũa', NULL, NULL),
(8, '메뉴', NULL, 'thực đơn', NULL, NULL),
(8, '컵', NULL, 'cốc, ly', NULL, NULL),
(8, '테이블', NULL, 'bàn ăn', NULL, NULL),
(8, '종업원', NULL, 'người phục vụ nhà hàng', NULL, NULL),
(8, '손님', NULL, 'khách', NULL, NULL),
(8, '흡연석', NULL, 'chỗ được hút thuốc lá', NULL, NULL),
(8, '금연석', NULL, 'chỗ cấm hút thuốc lá', NULL, NULL),
(8, '영수증', NULL, 'hóa đơn', NULL, NULL),
(8, '주문하다', NULL, 'gọi món', NULL, NULL),
(8, '계산하다', NULL, 'tính toán, tính tiền', NULL, NULL),
(8, '계산서', NULL, 'phiếu tính tiền', NULL, NULL),
(8, '가지', NULL, 'cà tím', NULL, NULL),
(8, '고추', NULL, 'ớt', NULL, NULL),
(8, '그래서', NULL, 'vì vậy', NULL, NULL),
(8, '기다리다', NULL, 'chờ đợi', NULL, NULL),
(8, '남편', NULL, 'chồng', NULL, NULL),
(8, '녹차', NULL, 'trà xanh', NULL, NULL),
(8, '더', NULL, 'thêm, nữa, càng', NULL, NULL),
(8, '드시다', NULL, 'dùng bữa (dạng kính ngữ của ''먹다'')', NULL, NULL),
(8, '레몬', NULL, 'chanh', NULL, NULL),
(8, '만들다', NULL, 'làm, tạo nên', NULL, NULL),
(8, '맛있게', NULL, 'một cách ngon lành', NULL, NULL),
(8, '물', NULL, 'nước', NULL, NULL),
(8, '반찬', NULL, 'món ăn phụ', NULL, NULL),
(8, '보통', NULL, 'bình thường', NULL, NULL),
(8, '소금', NULL, 'muối', NULL, NULL),
(8, '앉다', NULL, 'ngồi', NULL, NULL),
(8, '어서', NULL, 'xin mời', NULL, NULL),
(8, '음식', NULL, 'thức ăn', NULL, NULL),
(8, '인삼차', NULL, 'trà sâm', NULL, NULL),
(8, '잠깐만', NULL, 'chỉ một lát', NULL, NULL),
(8, '좀', NULL, 'một chút', NULL, NULL),
(8, '주다', NULL, 'cho', NULL, NULL),
(8, '콜라', NULL, 'Coca cola', NULL, NULL),
(8, '특히', NULL, 'đặc biệt', NULL, NULL)
ON DUPLICATE KEY UPDATE romanization=VALUES(romanization), meaning_vi=VALUES(meaning_vi);

INSERT INTO vocabulary (lesson_id, korean, romanization, meaning_vi, example_kr, example_vi) VALUES
(9, '위', NULL, 'trên', NULL, NULL),
(9, '아래', NULL, 'dưới', NULL, NULL),
(9, '안', NULL, 'trong', NULL, NULL),
(9, '밖', NULL, 'ngoài', NULL, NULL),
(9, '옆', NULL, 'bên cạnh', NULL, NULL),
(9, '사이', NULL, 'giữa', NULL, NULL),
(9, '앞', NULL, 'trước', NULL, NULL),
(9, '뒤', NULL, 'sau', NULL, NULL),
(9, '왼쪽', NULL, 'bên trái', NULL, NULL),
(9, '오른쪽', NULL, 'bên phải', NULL, NULL),
(9, '양쪽', NULL, 'hai phía', NULL, NULL),
(9, '건너편', NULL, 'đối diện', NULL, NULL),
(9, '맞은편', NULL, 'đối diện', NULL, NULL),
(9, '똑바로', NULL, 'thẳng', NULL, NULL),
(9, '쭉', NULL, 'thẳng', NULL, NULL),
(9, '동', NULL, 'đông', NULL, NULL),
(9, '서', NULL, 'tây', NULL, NULL),
(9, '남', NULL, 'nam', NULL, NULL),
(9, '북', NULL, 'bắc', NULL, NULL),
(9, '주택', NULL, 'nhà riêng', NULL, NULL),
(9, '아파트', NULL, 'nhà chung cư', NULL, NULL),
(9, '안방', NULL, 'phòng trung', NULL, NULL),
(9, '공부방', NULL, 'phòng học', NULL, NULL),
(9, '거실', NULL, 'phòng khách', NULL, NULL),
(9, '부엌', NULL, 'bếp', NULL, NULL),
(9, '현관', NULL, 'lối vào, cổng vào', NULL, NULL),
(9, '베란다', NULL, 'ban công', NULL, NULL),
(9, '오피스텔', NULL, 'nhà văn phòng', NULL, NULL),
(9, '세탁실', NULL, 'phòng giặt đồ', NULL, NULL),
(9, '침실', NULL, 'phòng ngủ', NULL, NULL),
(9, '침대', NULL, 'giường', NULL, NULL),
(9, '책장', NULL, 'tủ sách', NULL, NULL),
(9, '옷장', NULL, 'tủ quần áo', NULL, NULL),
(9, '소파', NULL, 'sa-lông, ghế sofa', NULL, NULL),
(9, '탁자', NULL, 'bàn', NULL, NULL),
(9, '식탁', NULL, 'bàn ăn', NULL, NULL),
(9, '화장대', NULL, 'bàn trang điểm', NULL, NULL),
(9, '신발장', NULL, 'tủ giày', NULL, NULL),
(9, '경찰서', NULL, 'sở cảnh sát', NULL, NULL),
(9, '세탁소', NULL, 'tiệm giặt ủi', NULL, NULL),
(9, '박물관', NULL, 'viện bảo tàng', NULL, NULL),
(9, '슈퍼마켓', NULL, 'siêu thị', NULL, NULL),
(9, '지하철역', NULL, 'ga tàu điện ngầm', NULL, NULL),
(9, '버스 정류장', NULL, 'trạm xe buýt', NULL, NULL),
(9, '빵집', NULL, 'tiệm bánh', NULL, NULL),
(9, '꽃집', NULL, 'tiệm bán hoa', NULL, NULL),
(9, '미용실', NULL, 'tiệm làm tóc nữ', NULL, NULL),
(9, '기숙사', NULL, 'ký túc xá', NULL, NULL),
(9, '단독주택', NULL, 'nhà đơn lập', NULL, NULL),
(9, '복잡하다', NULL, 'phức tạp', NULL, NULL),
(9, '불편하다', NULL, 'bất tiện', NULL, NULL),
(9, '사용하다', NULL, 'sử dụng, dùng', NULL, NULL),
(9, '자취 집', NULL, 'nhà thuê', NULL, NULL),
(9, '정원', NULL, 'vườn', NULL, NULL),
(9, '지내다', NULL, 'sống, trải qua', NULL, NULL),
(9, '지하', NULL, 'hầm, dưới lòng đất', NULL, NULL),
(9, '친절하다', NULL, 'thân thiện, tử tế', NULL, NULL),
(9, '편리하다', NULL, 'tiện lợi', NULL, NULL),
(9, '편하다', NULL, 'thoải mái', NULL, NULL),
(9, '하숙비', NULL, 'tiền thuê nhà trọ', NULL, NULL),
(9, '하숙집', NULL, 'nhà trọ', NULL, NULL),
(9, '혼자', NULL, 'một mình', NULL, NULL),
(10, '할아버지', NULL, 'ông nội', NULL, NULL),
(10, '할머니', NULL, 'bà nội', NULL, NULL),
(10, '외할아버지', NULL, 'ông ngoại', NULL, NULL),
(10, '외할머니', NULL, 'bà ngoại', NULL, NULL),
(10, '아버지', NULL, 'bố', NULL, NULL),
(10, '어머니', NULL, 'mẹ', NULL, NULL),
(10, '오빠', NULL, 'anh trai', NULL, NULL),
(10, '언니', NULL, 'chị gái', NULL, NULL),
(10, '나', NULL, 'tôi', NULL, NULL),
(10, '남동생', NULL, 'em trai', NULL, NULL),
(10, '누나', NULL, 'chị gái', NULL, NULL),
(10, '형', NULL, 'anh trai', NULL, NULL),
(10, '여동생', NULL, 'em gái', NULL, NULL),
(10, '교수', NULL, 'giáo sư', NULL, NULL),
(10, '연구원', NULL, 'người nghiên cứu', NULL, NULL),
(10, '군인', NULL, 'bộ đội', NULL, NULL),
(10, '사업가', NULL, 'doanh nhân', NULL, NULL),
(10, '변호사', NULL, 'luật sư', NULL, NULL),
(10, '경찰관', NULL, 'cảnh sát', NULL, NULL),
(10, '통역사', NULL, 'người thông dịch', NULL, NULL),
(10, '농부', NULL, 'nông dân', NULL, NULL),
(10, '사업을 하다', NULL, 'kinh doanh', NULL, NULL),
(10, '장사를 하다', NULL, 'buôn bán', NULL, NULL),
(10, '출장을 가다', NULL, 'đi công tác', NULL, NULL),
(10, '강아지', NULL, 'chó con, cún con', NULL, NULL),
(10, '결혼식', NULL, 'lễ cưới', NULL, NULL),
(10, '계시다', NULL, 'có, ở (kính ngữ)', NULL, NULL),
(10, '고모', NULL, 'cô', NULL, NULL),
(10, '고모부', NULL, 'dượng (chồng của cô)', NULL, NULL),
(10, '근무', NULL, 'làm việc', NULL, NULL),
(10, '근처', NULL, 'gần', NULL, NULL),
(10, '나중에', NULL, 'sau này', NULL, NULL),
(10, '대가족', NULL, 'đại gia đình', NULL, NULL),
(10, '댁', NULL, 'nhà (kính ngữ)', NULL, NULL),
(10, '돌아가시다', NULL, 'qua đời, trở về quá cố', NULL, NULL),
(10, '되다', NULL, 'trở thành', NULL, NULL),
(10, '딸', NULL, 'con gái', NULL, NULL),
(10, '말씀', NULL, 'lời nói', NULL, NULL)
ON DUPLICATE KEY UPDATE romanization=VALUES(romanization), meaning_vi=VALUES(meaning_vi);

INSERT INTO vocabulary (lesson_id, korean, romanization, meaning_vi, example_kr, example_vi) VALUES
(10, '말씀하시다', NULL, 'nói (kính ngữ)', NULL, NULL),
(10, '분', NULL, 'vị, người (kính ngữ)', NULL, NULL),
(10, '사촌', NULL, 'anh chị em họ', NULL, NULL),
(10, '삼촌', NULL, 'chú, cậu', NULL, NULL),
(10, '성함', NULL, 'tên, danh tính (kính ngữ)', NULL, NULL),
(10, '술', NULL, 'rượu', NULL, NULL),
(10, '아내', NULL, 'vợ', NULL, NULL),
(10, '아들', NULL, 'con trai', NULL, NULL),
(10, '열심히', NULL, 'một cách chăm chỉ', NULL, NULL),
(10, '올해', NULL, 'năm nay', NULL, NULL),
(10, '외동딸', NULL, 'con gái duy nhất', NULL, NULL),
(10, '외아들', NULL, 'con trai duy nhất', NULL, NULL),
(10, '유치원생', NULL, 'trẻ mẫu giáo', NULL, NULL),
(10, '잡수시다', NULL, 'ăn, dùng (kính ngữ)', NULL, NULL),
(10, '전공하다', NULL, 'học chuyên ngành', NULL, NULL),
(10, '주무시다', NULL, 'ngủ (kính ngữ)', NULL, NULL),
(10, '진지', NULL, 'cơm (kính ngữ)', NULL, NULL),
(10, '초등학생', NULL, 'học sinh tiểu học', NULL, NULL),
(10, '큰아버지', NULL, 'bác trai', NULL, NULL),
(10, '큰어머니', NULL, 'bác gái', NULL, NULL),
(11, '봄', NULL, 'mùa xuân', NULL, NULL),
(11, '여름', NULL, 'mùa hè', NULL, NULL),
(11, '가을', NULL, 'mùa thu', NULL, NULL),
(11, '겨울', NULL, 'mùa đông', NULL, NULL),
(11, '따뜻하다', NULL, 'ấm áp', NULL, NULL),
(11, '덥다', NULL, 'nóng', NULL, NULL),
(11, '쌀쌀하다', NULL, 'se se lạnh', NULL, NULL),
(11, '춥다', NULL, 'lạnh', NULL, NULL),
(11, '비가 오다', NULL, 'trời mưa', NULL, NULL),
(11, '비가 내리다', NULL, 'trời mưa', NULL, NULL),
(11, '비가 그치다', NULL, 'mưa tạnh', NULL, NULL),
(11, '눈이 오다', NULL, 'tuyết rơi', NULL, NULL),
(11, '눈이 내리다', NULL, 'tuyết rơi', NULL, NULL),
(11, '눈이 그치다', NULL, 'tuyết ngừng rơi', NULL, NULL),
(11, '맑다', NULL, 'trong', NULL, NULL),
(11, '흐리다', NULL, 'âm u', NULL, NULL),
(11, '바람이 불다', NULL, 'gió thổi', NULL, NULL),
(11, '구름이 끼다', NULL, 'nhiều mây', NULL, NULL),
(11, '해(태양)', NULL, 'mặt trời', NULL, NULL),
(11, '비', NULL, 'mưa', NULL, NULL),
(11, '눈', NULL, 'tuyết', NULL, NULL),
(11, '구름', NULL, 'mây', NULL, NULL),
(11, '기온', NULL, 'nhiệt độ không khí', NULL, NULL),
(11, '영상', NULL, 'trên không (độ), độ dương', NULL, NULL),
(11, '영하', NULL, 'dưới không (độ), độ âm', NULL, NULL),
(11, '도', NULL, 'độ', NULL, NULL),
(11, '가장', NULL, 'nhất', NULL, NULL),
(11, '곱다', NULL, 'đẹp, xinh xắn', NULL, NULL),
(11, '긴팔 옷', NULL, 'áo dài tay', NULL, NULL),
(11, '깨끗하다', NULL, 'sạch sẽ', NULL, NULL),
(11, '노란색', NULL, 'màu vàng', NULL, NULL),
(11, '단풍', NULL, 'lá phong, lá mùa thu', NULL, NULL),
(11, '답장', NULL, 'thư hồi âm', NULL, NULL),
(11, '도와주다', NULL, 'giúp đỡ cho', NULL, NULL),
(11, '돕다', NULL, 'giúp đỡ', NULL, NULL),
(11, '목도리', NULL, 'khăn quàng cổ', NULL, NULL),
(11, '반바지', NULL, 'quần soóc', NULL, NULL),
(11, '반팔 옷', NULL, 'áo cộc tay', NULL, NULL),
(11, '부츠', NULL, 'giày bốt, giày ống', NULL, NULL),
(11, '비슷하다', NULL, 'tương tự, giống', NULL, NULL),
(11, '스노보드', NULL, 'ván trượt tuyết', NULL, NULL),
(11, '스키장', NULL, 'sân trượt tuyết, khu trượt tuyết', NULL, NULL),
(11, '시끄럽다', NULL, 'ồn ào, ầm ĩ', NULL, NULL),
(11, '우산', NULL, 'ô/dù che mưa', NULL, NULL),
(11, '입다', NULL, 'mặc', NULL, NULL),
(11, '장갑', NULL, 'găng tay, bao tay', NULL, NULL),
(11, '좁다', NULL, 'hẹp', NULL, NULL),
(11, '추억', NULL, 'kỷ niệm, ký ức', NULL, NULL),
(11, '필요하다', NULL, 'cần thiết', NULL, NULL),
(11, '하늘', NULL, 'trời, bầu trời', NULL, NULL),
(11, '하얀 눈', NULL, 'tuyết trắng', NULL, NULL),
(11, '호수', NULL, 'hồ', NULL, NULL),
(12, '집 전화', NULL, 'điện thoại nhà riêng', NULL, NULL),
(12, '공중전화', NULL, 'điện thoại công cộng', NULL, NULL),
(12, '휴대전화', NULL, 'điện thoại di động', NULL, NULL),
(12, '전화번호', NULL, 'số điện thoại', NULL, NULL),
(12, '연락처', NULL, 'nơi liên lạc, số liên lạc', NULL, NULL),
(12, '전화 요금', NULL, 'phí điện thoại', NULL, NULL),
(12, '전화 카드', NULL, 'thẻ điện thoại', NULL, NULL),
(12, '국내 전화', NULL, 'điện thoại quốc nội', NULL, NULL),
(12, '국제전화', NULL, 'điện thoại quốc tế', NULL, NULL),
(12, '수신자 부담', NULL, 'điện thoại người nhận trả tiền', NULL, NULL),
(12, '인터넷 전화', NULL, 'điện thoại internet', NULL, NULL),
(12, '전화를 걸다', NULL, 'gọi điện thoại', NULL, NULL),
(12, '전화를 하다', NULL, 'gọi điện thoại', NULL, NULL),
(12, '전화가 오다', NULL, 'cuộc gọi đến', NULL, NULL),
(12, '전화를 받다', NULL, 'nhận điện thoại', NULL, NULL),
(12, '전화를 바꾸다', NULL, 'chuyển điện thoại (cho ai đó)', NULL, NULL),
(12, '전화를 끊다', NULL, 'kết thúc cuộc gọi', NULL, NULL),
(12, '통화 중이다', NULL, 'điện thoại bận, đang bận máy', NULL, NULL),
(12, '문자메시지를 보내다', NULL, 'gửi tin nhắn', NULL, NULL),
(12, '문자메시지를 받다', NULL, 'nhận tin nhắn', NULL, NULL),
(12, '답장을 보내다', NULL, 'gửi tin trả lời', NULL, NULL),
(12, '답장을 받다', NULL, 'nhận tin trả lời', NULL, NULL),
(12, '그분', NULL, 'vị ấy, người ấy', NULL, NULL),
(12, '깨우다', NULL, 'đánh thức', NULL, NULL),
(12, '남기다', NULL, 'để lại, còn lại', NULL, NULL),
(12, '내다', NULL, 'đưa ra', NULL, NULL),
(12, '늦게', NULL, 'muộn, trễ', NULL, NULL),
(12, '대사관', NULL, 'đại sứ quán', NULL, NULL)
ON DUPLICATE KEY UPDATE romanization=VALUES(romanization), meaning_vi=VALUES(meaning_vi);

INSERT INTO vocabulary (lesson_id, korean, romanization, meaning_vi, example_kr, example_vi) VALUES
(12, '들어오다', NULL, 'đi vào', NULL, NULL),
(12, '말씀 드리다', NULL, 'thưa chuyện, nói (kính ngữ)', NULL, NULL),
(12, '맞다', NULL, 'đúng', NULL, NULL),
(12, '사장님', NULL, 'giám đốc', NULL, NULL),
(12, '소리', NULL, 'âm thanh, tiếng', NULL, NULL),
(12, '약속', NULL, 'cuộc hẹn', NULL, NULL),
(12, '역사', NULL, 'lịch sử', NULL, NULL),
(12, '정하다', NULL, 'quyết định', NULL, NULL),
(12, '짐', NULL, 'hành lý', NULL, NULL),
(13, '생일', NULL, 'sinh nhật', NULL, NULL),
(13, '케이크', NULL, 'bánh kem', NULL, NULL),
(13, '축하 노래', NULL, 'bài hát chúc mừng', NULL, NULL),
(13, '잔치', NULL, 'tiệc', NULL, NULL),
(13, '카드', NULL, 'thiệp', NULL, NULL),
(13, '초대', NULL, 'mời', NULL, NULL),
(13, '나이', NULL, 'tuổi', NULL, NULL),
(13, '살', NULL, 'tuổi', NULL, NULL),
(13, '생신', NULL, 'kính ngữ của sinh nhật', NULL, NULL),
(13, '연세', NULL, 'kính ngữ của tuổi', NULL, NULL),
(13, '세', NULL, 'kính ngữ của tuổi', NULL, NULL),
(13, '지갑', NULL, 'cái ví', NULL, NULL),
(13, '화장품', NULL, 'mỹ phẩm', NULL, NULL),
(13, '손수건', NULL, 'khăn tay', NULL, NULL),
(13, '넥타이', NULL, 'cà vạt', NULL, NULL),
(13, '귀걸이', NULL, 'hoa tai, bông tai', NULL, NULL),
(13, '목걸이', NULL, 'dây chuyền', NULL, NULL),
(13, '반지', NULL, 'nhẫn', NULL, NULL),
(13, '꽃다발', NULL, 'lẵng hoa, bó hoa', NULL, NULL),
(13, '선물을 주다', NULL, 'tặng quà', NULL, NULL),
(13, '선물을 드리다', NULL, 'kính tặng quà', NULL, NULL),
(13, '선물을 받다', NULL, 'nhận quà', NULL, NULL),
(13, '선물을 고르다', NULL, 'chọn quà', NULL, NULL),
(13, '가볍다', NULL, 'nhẹ', NULL, NULL),
(13, '금반지', NULL, 'nhẫn vàng', NULL, NULL),
(13, '길다', NULL, 'dài', NULL, NULL),
(13, '꼭', NULL, 'nhất định', NULL, NULL),
(13, '레스토랑', NULL, 'restaurant, nhà hàng', NULL, NULL),
(13, '먼저', NULL, 'trước', NULL, NULL),
(13, '무겁다', NULL, 'nặng', NULL, NULL),
(13, '번째', NULL, 'lần', NULL, NULL),
(13, '부르다', NULL, 'gọi, hát', NULL, NULL),
(13, '생활', NULL, 'sinh hoạt', NULL, NULL),
(13, '스웨터', NULL, 'áo len', NULL, NULL),
(13, '스파게티', NULL, 'mì Ý', NULL, NULL),
(13, '시청', NULL, 'tòa thị chính', NULL, NULL),
(13, '아빠', NULL, 'ba, bố', NULL, NULL),
(13, '엄마', NULL, 'mẹ, má', NULL, NULL),
(13, '오래간만', NULL, 'lâu ngày không gặp', NULL, NULL),
(13, '웃다', NULL, 'cười', NULL, NULL),
(13, '이탈리아', NULL, 'Italy, Ý', NULL, NULL),
(13, '장미', NULL, 'hoa hồng', NULL, NULL),
(13, '짧다', NULL, 'ngắn', NULL, NULL),
(13, '참', NULL, 'rất', NULL, NULL),
(13, '첫', NULL, 'đầu tiên, thứ nhất', NULL, NULL),
(13, '피자', NULL, 'bánh pizza', NULL, NULL),
(13, '한식당', NULL, 'nhà hàng Hàn', NULL, NULL),
(13, '행복하다', NULL, 'hạnh phúc', NULL, NULL),
(13, '향수', NULL, 'nước hoa', NULL, NULL),
(13, '화장하다', NULL, 'trang điểm', NULL, NULL),
(13, '환갑', NULL, 'tiệc mừng thọ 60 tuổi', NULL, NULL),
(14, '축구', NULL, 'bóng đá', NULL, NULL),
(14, '농구', NULL, 'bóng rổ', NULL, NULL),
(14, '배구', NULL, 'bóng chuyền', NULL, NULL),
(14, '야구', NULL, 'bóng chày', NULL, NULL),
(14, '족구', NULL, 'bóng chuyền bằng chân', NULL, NULL),
(14, '탁구', NULL, 'bóng bàn', NULL, NULL),
(14, '배드민턴', NULL, 'cầu lông', NULL, NULL),
(14, '테니스', NULL, 'tennis', NULL, NULL),
(14, '태권도', NULL, 'Taekwondo', NULL, NULL),
(14, '골프', NULL, 'gôn', NULL, NULL),
(14, '스키', NULL, 'trượt tuyết', NULL, NULL),
(14, '요가', NULL, 'yoga', NULL, NULL),
(14, '마라톤', NULL, 'chạy ma-ra-tông', NULL, NULL),
(14, '스케이트', NULL, 'trượt băng', NULL, NULL),
(14, '볼링', NULL, 'bowling', NULL, NULL),
(14, '조깅', NULL, 'chạy bộ', NULL, NULL),
(14, '수영', NULL, 'bơi', NULL, NULL),
(14, '책 읽기', NULL, 'đọc sách', NULL, NULL),
(14, '독서', NULL, 'đọc sách', NULL, NULL),
(14, '사진 찍기', NULL, 'chụp ảnh', NULL, NULL),
(14, '그림 그리기', NULL, 'vẽ tranh', NULL, NULL),
(14, '음악 감상(하기)', NULL, 'nghe nhạc', NULL, NULL),
(14, '여행(하기)', NULL, 'đi du lịch', NULL, NULL),
(14, '운동(하기)', NULL, 'tập thể thao', NULL, NULL),
(14, '영화 보기', NULL, 'xem phim', NULL, NULL),
(14, '우표 수집', NULL, 'sưu tập tem', NULL, NULL),
(14, '우표 모으기', NULL, 'sưu tập tem', NULL, NULL),
(14, '컴퓨터 게임(하기)', NULL, 'chơi trò chơi điện tử', NULL, NULL),
(14, '항상', NULL, 'luôn luôn', NULL, NULL),
(14, '언제나', NULL, 'luôn luôn', NULL, NULL),
(14, '자주', NULL, 'thường xuyên', NULL, NULL),
(14, '가끔', NULL, 'thỉnh thoảng', NULL, NULL),
(14, '거의 안 ~', NULL, 'hầu như không...', NULL, NULL),
(14, '전혀', NULL, 'hoàn toàn', NULL, NULL),
(14, '잘하다', NULL, 'làm tốt', NULL, NULL),
(14, '못하다', NULL, 'không thể làm được', NULL, NULL),
(14, '보통이다', NULL, 'bình thường', NULL, NULL),
(14, '조금 하다', NULL, 'làm được một chút', NULL, NULL),
(14, '가곡', NULL, 'ca khúc, bài hát', NULL, NULL),
(14, '가요', NULL, 'dân ca', NULL, NULL)
ON DUPLICATE KEY UPDATE romanization=VALUES(romanization), meaning_vi=VALUES(meaning_vi);

INSERT INTO vocabulary (lesson_id, korean, romanization, meaning_vi, example_kr, example_vi) VALUES
(14, '걱정하다', NULL, 'lo lắng', NULL, NULL),
(14, '건강', NULL, 'sức khỏe', NULL, NULL),
(14, '걷다', NULL, 'đi bộ', NULL, NULL),
(14, '경기', NULL, 'trận đấu', NULL, NULL),
(14, '경치', NULL, 'cảnh vật, phong cảnh', NULL, NULL),
(14, '고등학교', NULL, 'trường trung học phổ thông', NULL, NULL),
(14, '기초', NULL, 'cơ sở, cơ bản', NULL, NULL),
(14, '도시락', NULL, 'cơm hộp', NULL, NULL),
(14, '동아리', NULL, 'câu lạc bộ', NULL, NULL),
(14, '디지털카메라', NULL, 'máy ảnh kỹ thuật số, digital camera', NULL, NULL),
(14, '만화책', NULL, 'truyện tranh', NULL, NULL),
(14, '묻다', NULL, 'hỏi', NULL, NULL),
(14, '믿다', NULL, 'tin, tin tưởng', NULL, NULL),
(14, '사진을 찍다', NULL, 'chụp ảnh', NULL, NULL),
(14, '아침마다', NULL, 'mỗi sáng', NULL, NULL),
(14, '앞으로', NULL, 'sau này, phía trước', NULL, NULL),
(14, '어렵다', NULL, 'khó', NULL, NULL),
(14, '유럽', NULL, 'châu Âu', NULL, NULL),
(14, '자막', NULL, 'phụ đề', NULL, NULL),
(14, '정도', NULL, 'mức độ, khoảng', NULL, NULL),
(14, '주로', NULL, 'chủ yếu', NULL, NULL),
(14, '준비물', NULL, 'đồ chuẩn bị', NULL, NULL),
(14, '채팅하다', NULL, 'chat', NULL, NULL),
(14, '취미', NULL, 'thú vui, sở thích', NULL, NULL),
(14, '통역하다', NULL, 'thông dịch', NULL, NULL),
(14, '특기', NULL, 'đặc biệt', NULL, NULL),
(14, '피아노', NULL, 'piano, đàn dương cầm', NULL, NULL),
(14, '한글', NULL, 'chữ Hangeul', NULL, NULL),
(14, '해외여행', NULL, 'du lịch nước ngoài', NULL, NULL),
(15, '버스', NULL, 'xe buýt', NULL, NULL),
(15, '기차', NULL, 'tàu hỏa', NULL, NULL),
(15, '택시', NULL, 'taxi', NULL, NULL),
(15, '지하철', NULL, 'tàu điện ngầm', NULL, NULL),
(15, '오토바이', NULL, 'xe máy', NULL, NULL),
(15, '자동차', NULL, 'ô tô', NULL, NULL),
(15, '배', NULL, 'thuyền', NULL, NULL),
(15, '비행기', NULL, 'máy bay', NULL, NULL),
(15, '자전거', NULL, 'xe đạp', NULL, NULL),
(15, '전차', NULL, 'tàu điện', NULL, NULL),
(15, '세옴', NULL, 'xe ôm', NULL, NULL),
(15, '시클로', NULL, 'xích lô', NULL, NULL),
(15, '어떻게', NULL, 'như thế nào', NULL, NULL),
(15, '얼마나', NULL, 'bao nhiêu, bao lâu', NULL, NULL),
(15, '왜', NULL, 'tại sao', NULL, NULL),
(15, '모범택시', NULL, 'taxi cao cấp', NULL, NULL),
(15, '개인택시', NULL, 'taxi cá nhân', NULL, NULL),
(15, '요금', NULL, 'tiền vé, cước phí', NULL, NULL),
(15, '버스 정거장', NULL, 'điểm dừng xe buýt, trạm xe buýt', NULL, NULL),
(15, '고속버스', NULL, 'xe buýt cao tốc', NULL, NULL),
(15, '시내버스', NULL, 'xe buýt nội thành', NULL, NULL),
(15, '버스 터미널', NULL, 'bến xe khách', NULL, NULL),
(15, '교통 카드', NULL, 'thẻ giao thông', NULL, NULL),
(15, '마을버스', NULL, 'xe buýt tuyến ngắn', NULL, NULL),
(15, '매표소', NULL, 'quầy vé', NULL, NULL),
(15, '지하철 노선도', NULL, 'bản đồ tuyến tàu điện ngầm', NULL, NULL),
(15, '기차역', NULL, 'ga tàu hỏa', NULL, NULL),
(15, '공항', NULL, 'sân bay', NULL, NULL),
(15, '주차장', NULL, 'bãi đỗ xe', NULL, NULL),
(15, '주유소', NULL, 'trạm xăng', NULL, NULL),
(15, '횡단보도', NULL, 'vạch/lối băng sang đường', NULL, NULL),
(15, '육교', NULL, 'cầu vượt', NULL, NULL),
(15, '지하도', NULL, 'đường hầm', NULL, NULL),
(15, '신호등', NULL, 'đèn tín hiệu giao thông', NULL, NULL),
(15, '고속도로', NULL, 'đường cao tốc', NULL, NULL),
(15, '도로', NULL, 'đường, đại lộ', NULL, NULL),
(15, '타다', NULL, 'lên, đi (phương tiện giao thông)', NULL, NULL),
(15, '내리다', NULL, 'xuống', NULL, NULL),
(15, '갈아타다', NULL, 'đổi (phương tiện giao thông)', NULL, NULL),
(15, '길이 막히다', NULL, 'tắc đường', NULL, NULL),
(15, '시간이 걸리다', NULL, 'mất thời gian', NULL, NULL),
(15, '교통사고가 나다', NULL, 'xảy ra tai nạn giao thông', NULL, NULL),
(15, '간식', NULL, 'bữa phụ, quà vặt', NULL, NULL),
(15, '남산', NULL, 'núi Namsan', NULL, NULL),
(15, '노랗다', NULL, 'màu vàng', NULL, NULL),
(15, '리무진 버스', NULL, 'xe buýt cao cấp thường là xe buýt đi sân bay, xe đưa đón ở khách sạn cao cấp, xe buýt lớn hạng sang', NULL, NULL),
(15, '빨갛다', NULL, 'đỏ', NULL, NULL),
(15, '야경', NULL, 'quang cảnh buổi tối', NULL, NULL),
(15, '요리 학원', NULL, 'trung tâm dạy nấu ăn', NULL, NULL),
(15, '지각하다', NULL, 'muộn, trễ', NULL, NULL),
(15, '파랗다', NULL, 'xanh da trời', NULL, NULL),
(15, '편의점', NULL, 'cửa hàng tiện lợi', NULL, NULL),
(15, '학생회관', NULL, 'hội quán sinh viên', NULL, NULL),
(15, 'KTX', NULL, 'tàu cao tốc', NULL, NULL)
ON DUPLICATE KEY UPDATE romanization=VALUES(romanization), meaning_vi=VALUES(meaning_vi);

COMMIT;

-- Canonical vocabulary rows in this hotfix: 783